export const states = [
  {
    tileState: [
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 1,
        stepGain: -1,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: -1.3333333333333333,
        coinGain: -2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
    ],
    normalizedHeartsRemaining: 1,
    normalizedStepsRemaining: 0.98,
  },
  {
    tileState: [
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 1,
        stepGain: -1,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: -1.3333333333333333,
        coinGain: -2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
    ],
    normalizedHeartsRemaining: 1,
    normalizedStepsRemaining: 0.98,
  },
  {
    tileState: [
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 1,
        stepGain: -1,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: -1.3333333333333333,
        coinGain: -2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
    ],
    normalizedHeartsRemaining: 1,
    normalizedStepsRemaining: 0.98,
  },
  {
    tileState: [
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: -1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 1,
        stepGain: -1,
        dirX: -1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 0,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -1,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: -1.3333333333333333,
        coinGain: -2,
        stepGain: -0.6666666666666666,
        dirX: -1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 0,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
      {
        heartGain: 0,
        coinGain: 0,
        stepGain: 0,
        dirX: 1,
        dirY: 1,
      },
    ],
    normalizedHeartsRemaining: 1,
    normalizedStepsRemaining: 0.98,
  },
]
